### PR TITLE
Add capability to whitelist requests

### PR DESCRIPTION
**Pull request by schaeferthomas**
Allow a user to implement a custom whitelisting Class based on a WhitelistInterface. This will allow e.g. easy IP whitelisting.

### CODE REVIEW

**Comment by mcfedr** [comment]
Thanks for the contribution, we have recently added the `CheckedRateLimit` Event, which will also allow you to solve this, and can be more flexible for other uses, so unfortunately I'm not going to merge this. I think it will be very simple for you to adapter your whitelisting class to receive the event and use that for white listing.

**Comment by schaeferthomas** [comment]
The problem with the `CheckedRateLimit` Event was for me, that I did not find any way to reset or even not set the rate limit. Did I overlook something?

**Comment by mcfedr** [comment]
on the event object that is given, you can call `setRateLimit(null)`, which will remove any rate limiting.

**Comment by schaeferthomas** [comment]
Perfect 👍

**Pull request closed without merging**
