### PR TITLE
Support for Symfony 3

### PR DESCRIPTION
**Pull request by peshi**
SecurityContext was removed in 3.0 - the purpose of this PR is to provide a BC layer for older versions of Symfony.

### CODE REVIEW

**Comment by peshi** [comment]
Test should pass once FOSOAuthServerBundle is updated for Symfony 3

**Comment by thomask** [comment]
Awesome, was just about to start on this PR myself. Hope this'll get merged soon.

**Comment by jaytaph** [comment]
I will try and see if I can merge this today/tomorrow, time permitting.. I probably need some SF3 support in the near future myself as well :)

**Comment by jaytaph** [comment]
@peshi Thanks for your work! Much appreciated. We'll probably want to support the 2.3 version for a while, and I'm really hoping FOSOAuth will be upgraded soon too (https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/374)

**Comment by peshi** [comment]
@jaytaph No worries, thank you for merging :+1:

**Pull request merged**
