### PR TITLE
Fixes for different symfony versions

### PR DESCRIPTION
**Pull request by jaytaph**
To test:

you might want to remove the fos/oauth-server dependency, otherwise symfony 5 will not install.

```shell
composer require "symfony/symfony:5.0.x" --no-update
composer update
./vendor/bin/phpunit

composer require "symfony/symfony:4.4.x" --no-update
composer update
./vendor/bin/phpunit

composer require "symfony/symfony:4.3.x" --no-update
composer update
./vendor/bin/phpunit

composer require "symfony/symfony:3.4.x" --no-update
composer update
./vendor/bin/phpunit
```

### CODE REVIEW

**Comment by jaytaph** [comment]
@goetas @KDederichs  What do you think?

**Comment by KDederichs** [comment]
And yeah that oAuth dependency is kind of annoying, I've seen the NelmioBundle removing it in Travis on SF5 tests via before_install so that's probably the best option here.
Especially since you already changed the test to work without it

**Comment by jaytaph** [comment]
@KDederichs I'm removing the FOS bundle for Symfony 5 and it passes. The only thing that doesn't pass is the prefer-lowest because of some mismatch of the `tearDown` method between PHPUnit and Symfony TestCase. I think this will be ok enough.

If this PR can be greenlit, I will merge and tag a 1.15.1 release.

**Comment by mcfedr** [comment]
LGTM

**Comment by KDederichs** [comment]
Awesome 👍

**Pull request merged**
