### PR TITLE
Symfony 6 support

### PR DESCRIPTION
**Pull request by goetas**

### CODE REVIEW

**Comment by goetas** [comment]
@jaytaph  if you are interested in this, it is ready for your preview

it adds symfony 6.1 support and improves a little the CI

**Comment by jaytaph** [comment]
Hi @goetas  sorry for the delay. I'll take a look at it today.

**Review by jaytaph — APPROVED** [review]

**Comment by goetas** [comment]
thanks to you!

**Comment by goetas** [comment]
it would be great to have a new tagged release

**Comment by jaytaph** [comment]
Tagged as v1.19.0.

Thanks for the PR

**Pull request merged**
