### PR TITLE
update/symfony-4.3

### PR DESCRIPTION
**Pull request by AlexRapso**
update: symfony 4.3
fix: deprecations and tests.

### CODE REVIEW

**Comment by mcfedr** [comment]
is this backwards compatible?

**Comment by goetas** [comment]
> is this backwards compatible?

looking at the test failures, it is not

**Comment by jaytaph** [comment]
No, `FilterResponseEvent` is marked deprecated in Symfony 4.3, but we need to maintain it for the 2.x, 3.x and 4.x branches. It can be safely changed once we will only support symfony 5+ (which i doubt will be soon).

The PR looks good, but I don't think we could make these changes right now.

**Comment by goetas** [comment]
> The PR looks good, but I don't think we could make these changes right now.

I share your opinion. Dropping support for 2.x, 3.x and 4.x (<4.3) branches is not a good idea (and I guess there is a way to make it backward compatible).

**Comment by DemigodCode** [comment]
Take a look at https://github.com/jaytaph/RateLimitBundle/pull/90 please

**Comment by jaytaph** [comment]
@AlexRapso  Thanks for your work. We just released a new 1.15.0 release that will be compatible with 3.4+, 4.3+ and 5.x releases

**Pull request closed without merging**
